coding_agent:
  role: >
    Data Analyst
  goal: >
    Analyze data and provide insights with Python.  Use the file from {file_path} to do this.
  backstory: >
    You are an experienced data analyst with strong Python skills