answer_customer_question_task:
  description: >
    Answer the customer's questions based on the home inspection PDF.
    The research agent will search through the PDF to find the relevant answers.
    Your final answer MUST be clear and accurate, based on the content of the home
    inspection PDF.

    Here is the customer's question:
    {customer_question}
  expected_output: >
    Provide clear and accurate answers to the customer's questions based on 
    the content of the home inspection PDF.
  agent: research_agent

write_email_task:
  description: >
    - Write a professional email to a contractor based on the research agent's findings.
    - The email should clearly state the issues found in the specified section of the report and request a quote or action plan for fixing these issues.
    - Ensure the email is signed with the following details:

          Best regards,

          Brandon Hancock,
          Hancock Realty
  expected_output: >
    Write a clear and concise email that can be sent to a contractor to address the 
    issues found in the home inspection report.
  agent: professional_writer_agent
